### PR TITLE
dllmain better createthread

### PR DESCRIPTION
**Pull request by retarded-person**
i would consider using std::jthread but ur dont have the std::unique_ptr poopy stuff

### CODE REVIEW

**Review by st3ph4nnn — COMMENTED** [review]
DisableThreadLibraryCalls( hinstDLL ); makes no sense in that context

**Comment by retarded-person** [comment]
ok

**Comment by retarded-person** [comment]
do it anyway doesnt do any harm and apparently is an optimization

**Comment by PancakeWithPotato** [comment]
n0

**Pull request closed without merging**
